### ISSUE TITLE
[Feat] Connecting hosts and containers

### ISSUE THREAD

**Issue by yeoniii20** [Team-Goraebab/Goraebab-Frontend#16]
# ToDo 🍄

### components 🍥
> DND 적용 이후 사용하시면 좋을것 같습니다

### 1. cardContainer 🍋

- [x] name/ip/status props으로 전달 
- [x] status (running/stopped)에 따라 초록불/빨간불로 구분
- [x] 일정 높이가 되면 스크롤로 확인 가능 (스크롤은 ui에 나타나지 않도록함)

### 2. connectBar 🍬

- [x] hostCard와 containerCard를 연결하는 컴포넌트
- [x] 현재 길이 조절은 불가능함 (props으로 길이 전달 시 조절 가능)
- [x] hostCard와 containerCard 사이에 넣으면 됨 (위치는 hostCard 상단에 고정되어 있음)
