### ISSUE TITLE
[Feat] Layout UI

### ISSUE THREAD

**Issue by yeoniii20** [Team-Goraebab/Goraebab-Frontend#20]
# Todo 🙋🏻

### 1. Card

- [x] card component
- [ ] 오른쪽 상단 옵션 버튼, 드래그 기능

### 2. Button

- [x] buttoncomponent
- [ ] 관련 기능

### 1. Header

- [x] header component (임시 아이콘 사용)
- [x] 하단 바 슬라이드 애니매이션 추가

### 2. Sidebar

- [x] 모든 페이지에 고정으로 들어가 있기 때문에 layout에 import
- [x] scroll hidden 처리
