### ISSUE TITLE
[Feat] Create Components

### ISSUE THREAD

**Issue by yeoniii20** [Team-Goraebab/Goraebab-Frontend#21]
# Todo 🌴

### 1. hostCard 🧼

- [x] hostCard 구현
- [x] connect/disconnect status Props으로 전달

### 2. zoomButtons Section 🐠

- [x] zoomButtons Section 구현
- [x] 최소 50% 최대 200% 로 limt 지정
 

### 3. panButtons Section 🚿

- [x] panButtons Section 구현 (임시 아이콘 사용)
- [x] cursor만 변경 (기능 미구현)

<br />

# 수정 사항 🎃

### React:FC 삭제

- [x] React:FC 삭제

### components에 index.ts 생성 후 file path 정의

- [x] components에 index.ts 생성 후 file path 정의
- [x] components import file path 전체 수정

### store, data file을 src 내부로 이동

- [x] store, data file을 src 내부로 이동
- [x] 경로 별칭으로 file path 변경
