### ISSUE TITLE
[FIX] Create container 

### ISSUE THREAD

**Issue by yeoniii20** [Team-Goraebab/Goraebab-Frontend#40]
# Todo
> Error occurred while creating container

- [x] edit create container
- [x] edit container store
- [x] edit view container info
