### ISSUE TITLE
[FEAT] Docker Connection Status

### ISSUE THREAD

**Issue by yeoniii20** [Team-Goraebab/Goraebab-Frontend#42]
# Todo
> Checks whether the Docker engine is running and reports the daemon connection status

- [x] Check if the Docker engine is running
- [x] Check the daemon connection status
- [x] Display connection status at the bottom of the sidebar
