### ISSUE TITLE
[Feat] Blueprints and Add function

### ISSUE THREAD

**Issue by yeoniii20** [Team-Goraebab/Goraebab-Frontend#57]
# Todo 📌

### Blueprint 🧩

- [x] Create a host
- [x] Connect a network to the host
- [x] Launch a container on the network
- [x] Save the blueprint

### Container 🚧

- [x] Run container
- [x] Stop container
- [ ] Pause container
- [x] Kill container
- [x] Check container resource usage

### Network 🖥️

- [x] Connect container to network
- [x] Disconnect network connected to container
