### ISSUE TITLE
[Feat] Remote and Feedback

### ISSUE THREAD

**Issue by yeoniii20** [Team-Goraebab/Goraebab-Frontend#70]
# Todo

### Api
- [x] Create remote daemon
- [x] Create remote database

### Feedback
- [x] Fix sidebar volume data issue
- [x] Add accordion to network card
